service: aws-py-test
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: us-east-2

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - httpApi:
          path: /time
          method: get